using Conduit.Presentation.Extensions;

using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;

namespace Conduit.Presentation.Transformers;

internal sealed class ConduitOpenApiDocumentTransformer(string apiPrefix) : IOpenApiDocumentTransformer
{
    private static readonly Uri DocumentationUri = new("https://realworld-docs.netlify.app/");
    private static readonly Uri LicenseUri = new("https://opensource.org/licenses/MIT");

    public Task TransformAsync(
        OpenApiDocument document,
        OpenApiDocumentTransformerContext context,
        CancellationToken cancellationToken)
    {
        document.Info.Title = "RealWorld Conduit API";
        document.Info.Description = "Conduit API documentation";
        document.Info.Version = "2.0.0";
        document.Info.Contact = new OpenApiContact
        {
            Name = "RealWorld",
            Url = DocumentationUri
        };
        document.Info.License = new OpenApiLicense
        {
            Name = "MIT License",
            Url = LicenseUri
        };

        document.MovePathPrefixToServer(apiPrefix);

        document.Components ??= new OpenApiComponents();
        document.Components.SecuritySchemes ??= new Dictionary<string, IOpenApiSecurityScheme>();
        document.Components.SecuritySchemes.TryAdd("Token", new OpenApiSecurityScheme
        {
            Type = SecuritySchemeType.ApiKey,
            Name = "Authorization",
            In = ParameterLocation.Header,
            Description = """
                For accessing the protected API resources, you must have received a a valid JWT token after registering or logging in. This JWT token must then be used for all protected resources by passing it in via the 'Authorization' header.

                A JWT token is generated by the API by either registering via /users or logging in via /users/login.

                The following format must be in the 'Authorization' header :

                    Token xxxxxx.yyyyyyy.zzzzzz

                """ + "    \n"
        });

        document.Tags = new HashSet<OpenApiTag>
        {
            new() { Name = "Articles", Description = "Everything about your Articles" },
            new() { Name = "Comments", Description = "Everything about your Comments" },
            new() { Name = "Favorites", Description = "Everything about your Favorites" },
            new() { Name = "Profile", Description = "Everything about your Profile" },
            new() { Name = "Tags", Description = "Everything about your Tags" },
            new()
            {
                Name = "User and Authentication",
                Description = "Everything about your User and Authentication"
            }
        };

        return Task.CompletedTask;
    }
}