version: "3"

tasks:
  install:
    cmds:
      - dotnet tool restore
      - dotnet restore
  lint:
    cmds:
      - dotnet format --verify-no-changes
  build:
    cmds:
      - dotnet sonarscanner begin /k:"{{.SONARQUBE_PROJECT_KEY}}" /d:sonar.host.url="{{.SONARQUBE_URL}}" /d:sonar.token="{{.SONARQUBE_ANALYSIS_TOKEN}}" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
      - dotnet build -c Release
  test:
    cmds:
      - dotnet coverage collect 'dotnet test -c Release --no-restore --no-build --verbosity=normal' -f xml -o 'coverage.xml'
      - dotnet sonarscanner end /d:sonar.token="{{.SONARQUBE_ANALYSIS_TOKEN}}"
      - dotnet publish src/Conduit.WebUI -c Release -o publish --no-restore --no-build --verbosity=normal
      - dotnet publish tools/Conduit.Tools -c Release -o publish --no-restore --no-build --verbosity=normal
