on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: node-bookworm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
          cache: true
          cache-dependency-path: "**/packages.lock.json"
      - uses: https://forgejo.okami101.io/okami101/actions/task@main
        env:
          SONARQUBE_URL: ${{ vars.SONAR_HOST_URL }}
          SONARQUBE_ANALYSIS_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONARQUBE_PROJECT_KEY: aspnet-core-realworld
      - uses: https://forgejo.okami101.io/okami101/actions/docker@main
        with:
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          repository: ${{ gitea.repository }}
          token: ${{ secrets.RELEASE_TOKEN }}
          release: true
