on:
  push:
    branches:
      - main

jobs:
  test_docker:
    runs-on: docker-cli
    steps:
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: test/${{ forge.repository }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=semver,pattern={{raw}},value=test
  # build:
  #   runs-on: node-bookworm
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-java@v4
  #       with:
  #         distribution: "temurin"
  #         java-version: 21
  #     - name: Cache SonarQube packages
  #       uses: actions/cache@v4
  #       with:
  #         path: ~/.sonar/cache
  #         key: ${{ runner.os }}-sonar
  #     - uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: 9.x
  #         cache: true
  #         cache-dependency-path: "**/packages.lock.json"
  #     - uses: https://forge.okami101.io/okami101/actions/task@main
  #       env:
  #         SONARQUBE_URL: ${{ vars.SONAR_HOST_URL }}
  #         SONARQUBE_ANALYSIS_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #         SONARQUBE_PROJECT_KEY: aspnet-core-realworld
  #     - uses: https://forge.okami101.io/okami101/actions/docker@main
  #       with:
  #         password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
  #         gitea-token: ${{ secrets.RELEASE_TOKEN }}
  #         release: true
