on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 21
      - name: Cache SonarQube packages
        uses: actions/cache@v5
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.x
          cache: true
          cache-dependency-path: "**/packages.lock.json"
      - uses: jdx/mise-action@v3
        with:
          install: false
      - run: mise ci
        env:
          MISE_TASK_RUN_AUTO_INSTALL: false
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - uses: https://gitea.okami101.io/okami101/actions/docker@main
        with:
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          gitea-token: ${{ secrets.RELEASE_TOKEN }}
          release: true
