offsetParam:
  in: query
  name: offset
  required: false
  schema:
    type: integer
    minimum: 0
  description: The number of items to skip before starting to collect the result set.
limitParam:
  in: query
  name: limit
  required: false
  schema:
    type: integer
    minimum: 1
    default: 20
  description: The numbers of items to return.
